#include "AuthController.h"
#include "../utils/JwtUtils.h"
#include "../models/Users.h"   // generated by drogon_ctl (see Part 3 note)
#include <drogon/orm/Mapper.h>
#include <bcrypt/bcrypt.h>
#include <json/json.h>

using namespace drogon::orm;
using namespace drogon_model;  // namespace drogon_ctl generates models into

/**
 * INTERVIEW DEFENSE NOTE:
 * Registration flow:
 * 1. Validates required payload fields (name, email, password, role).
 * 2. Role is strictly restricted to enum values: 'government' | 'startup'.
 * 3. Uses bcrypt to hash password with an automatically generated cryptographic salt.
 * 4. Inserts via Drogon ORM Mapper. Any DB UNIQUE constraint violation on email
 *    is caught in the exception callback and mapped to a clean HTTP 409 Conflict.
 * 5. Returns HTTP 201 Created with the signed JWT token.
 */
void AuthController::registerUser(const drogon::HttpRequestPtr &req,
                                   std::function<void(const drogon::HttpResponsePtr &)> &&callback)
{
    auto json = req->getJsonObject();
    if (!json || !(*json).isMember("email") || !(*json).isMember("password") ||
        !(*json).isMember("name") || !(*json).isMember("role"))
    {
        auto resp = drogon::HttpResponse::newHttpResponse();
        resp->setStatusCode(drogon::k400BadRequest);
        resp->setBody("name, email, password, role are required");
        callback(resp);
        return;
    }

    std::string name = (*json)["name"].asString();
    std::string email = (*json)["email"].asString();
    std::string password = (*json)["password"].asString();
    std::string role = (*json)["role"].asString();  // "government" | "startup"

    if (role != "government" && role != "startup")
    {
        auto resp = drogon::HttpResponse::newHttpResponse();
        resp->setStatusCode(drogon::k400BadRequest);
        resp->setBody("role must be 'government' or 'startup'");
        callback(resp);
        return;
    }

    // bcrypt handles its own salt generation internally — one call,
    // nothing extra to store or manage ourselves.
    std::string hashedPassword = bcrypt::generateHash(password);

    Users user;
    user.setName(name);
    user.setEmail(email);
    user.setPasswordHash(hashedPassword);
    user.setRole(role);

    auto dbClient = drogon::app().getDbClient();
    Mapper<Users> mapper(dbClient);

    mapper.insert(
        user,
        [callback](Users inserted) {
            std::string token = encodeToken(inserted.getValueOfId(), inserted.getValueOfRole());

            Json::Value result;
            result["token"] = token;
            result["userId"] = inserted.getValueOfId();
            result["role"] = inserted.getValueOfRole();

            auto resp = drogon::HttpResponse::newHttpJsonResponse(result);
            resp->setStatusCode(drogon::k201Created);
            callback(resp);
        },
        [callback](const DrogonDbException &e) {
            // Most common cause: UNIQUE violation on email.
            auto resp = drogon::HttpResponse::newHttpResponse();
            resp->setStatusCode(drogon::k409Conflict);
            resp->setBody("Email already registered");
            callback(resp);
        });
}

/**
 * INTERVIEW DEFENSE NOTE:
 * Login flow:
 * 1. Looks up the single user record by email using Drogon Mapper Criteria.
 * 2. Uses constant-time bcrypt comparison to prevent timing attacks.
 * 3. Returns 401 Unauthorized for both "email not found" and "incorrect password"
 *    to avoid user enumeration attacks.
 * 4. Signs a 24-hour JWT containing { userId, role } on success.
 */
void AuthController::login(const drogon::HttpRequestPtr &req,
                            std::function<void(const drogon::HttpResponsePtr &)> &&callback)
{
    auto json = req->getJsonObject();
    if (!json || !(*json).isMember("email") || !(*json).isMember("password"))
    {
        auto resp = drogon::HttpResponse::newHttpResponse();
        resp->setStatusCode(drogon::k400BadRequest);
        resp->setBody("email and password are required");
        callback(resp);
        return;
    }

    std::string email = (*json)["email"].asString();
    std::string password = (*json)["password"].asString();

    auto dbClient = drogon::app().getDbClient();
    Mapper<Users> mapper(dbClient);

    mapper.findBy(
        Criteria(Users::Cols::_email, CompareOperator::EQ, email),
        [password, callback](std::vector<Users> users) {
            if (users.empty() || !bcrypt::validatePassword(password, users[0].getValueOfPasswordHash()))
            {
                auto resp = drogon::HttpResponse::newHttpResponse();
                resp->setStatusCode(drogon::k401Unauthorized);
                resp->setBody("Invalid email or password");
                callback(resp);
                return;
            }

            auto &user = users[0];
            std::string token = encodeToken(user.getValueOfId(), user.getValueOfRole());

            Json::Value result;
            result["token"] = token;
            result["userId"] = user.getValueOfId();
            result["role"] = user.getValueOfRole();

            callback(drogon::HttpResponse::newHttpJsonResponse(result));
        },
        [callback](const DrogonDbException &e) {
            auto resp = drogon::HttpResponse::newHttpResponse();
            resp->setStatusCode(drogon::k500InternalServerError);
            callback(resp);
        });
}
