import { useEffect, useState } from "react";
import { useParams, Link } from "react-router-dom";
import { apiFetch } from "../api/client";

interface RankedEntry {
  rank: number;
  application_id: number;
  startup_id: number;
  final_score: number;
}

interface CriterionBreakdown {
  criterion: string;
  raw_score: number;
  weighted_score: number;
  max_weighted_score: number;
}

interface Breakdown {
  breakdown: CriterionBreakdown[];
  final_score: number;
  rank: number;
}

export default function Rankings() {
  const { id } = useParams();
  const [rankings, setRankings] = useState<RankedEntry[]>([]);
  // Cache of breakdown per application_id — powers both the single-startup
  // drill-down and the side-by-side comparison table below, so we don't
  // fetch the same breakdown twice.
  const [breakdowns, setBreakdowns] = useState<Record<number, Breakdown>>({});
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    setLoading(true);
    apiFetch<RankedEntry[]>(`/projects/${id}/rankings`)
      .then(async (list) => {
        setRankings(list || []);
        if (list && list.length > 0) {
          const entries = await Promise.all(
            list.map(async (r) => {
              try {
                const bd = await apiFetch<Breakdown>(`/applications/${r.application_id}/breakdown`);
                return [r.application_id, bd] as const;
              } catch (e) {
                return [r.application_id, { breakdown: [], final_score: r.final_score, rank: r.rank }] as const;
              }
            })
          );
          setBreakdowns(Object.fromEntries(entries));
        }
        setLoading(false);
      })
      .catch((err) => {
        setError((err as Error).message || "Failed to load rankings");
        setLoading(false);
      });
  }, [id]);

  const criterionNames = rankings.length && breakdowns[rankings[0].application_id]
    ? breakdowns[rankings[0].application_id]?.breakdown.map((b) => b.criterion) ?? []
    : [];

  return (
    <div style={{ maxWidth: 850, margin: "40px auto", fontFamily: "sans-serif" }}>
      <div style={{ marginBottom: 16 }}>
        <Link to="/government">← Back to Government Dashboard</Link>
        {" | "}
        <Link to={`/projects/${id}`}>View Project Details</Link>
      </div>

      <h2>Ranked Startups Leaderboard</h2>
      <p style={{ color: "#555" }}>
        Deterministic ranking generated by the C++ Ranking Engine over all <code>ELIGIBLE</code> proposals.
      </p>

      {loading && <p>Computing & fetching rankings from C++ engine...</p>}
      {error && <p style={{ color: "red" }}>{error}</p>}

      {!loading && rankings.length === 0 && (
        <p style={{ color: "#666" }}>No eligible startup applications submitted yet.</p>
      )}

      {!loading && rankings.length > 0 && (
        <>
          <table border={1} cellPadding={8} style={{ borderCollapse: "collapse", width: "100%", marginTop: 12 }}>
            <thead>
              <tr style={{ background: "#f5f5f5" }}>
                <th align="center">Rank</th>
                <th align="left">Startup ID</th>
                <th align="right">Final Score (0-100)</th>
              </tr>
            </thead>
            <tbody>
              {rankings.map((r) => (
                <tr key={r.application_id} style={{ background: r.rank === 1 ? "#e8f5e9" : "transparent" }}>
                  <td align="center">
                    <strong>#{r.rank}</strong>
                    {r.rank === 1 && " 🏆"}
                  </td>
                  <td>Startup #{r.startup_id}</td>
                  <td align="right">
                    <strong>{r.final_score.toFixed(1)}</strong>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>

          <h2 style={{ marginTop: 40 }}>Comparison (Explainable Breakdown)</h2>
          <p style={{ color: "#666", fontSize: 14 }}>
            Detailed breakdown showing raw scores normalized and multiplied by dynamic criteria weights:
          </p>

          <table border={1} cellPadding={8} style={{ borderCollapse: "collapse", width: "100%", marginTop: 12 }}>
            <thead>
              <tr style={{ background: "#f5f5f5" }}>
                <th align="left">Criterion</th>
                {rankings.map((r) => (
                  <th key={r.application_id} align="center">Startup #{r.startup_id}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {criterionNames.map((name) => (
                <tr key={name}>
                  <td><strong>{name}</strong></td>
                  {rankings.map((r) => {
                    const b = breakdowns[r.application_id]?.breakdown.find((x) => x.criterion === name);
                    return (
                      <td key={r.application_id} align="center">
                        {b ? `${b.weighted_score.toFixed(1)} / ${b.max_weighted_score}` : "-"}
                      </td>
                    );
                  })}
                </tr>
              ))}
              <tr style={{ background: "#f9f9f9" }}>
                <td><strong>Final Score</strong></td>
                {rankings.map((r) => (
                  <td key={r.application_id} align="center">
                    <strong style={{ color: "#0066cc" }}>{r.final_score.toFixed(1)}</strong>
                  </td>
                ))}
              </tr>
            </tbody>
          </table>

          <p style={{ marginTop: 24, fontStyle: "italic", color: "#666", fontSize: 13 }}>
            This ranking is an explainable decision-support tool. The final procurement decision
            remains with the government.
          </p>
        </>
      )}
    </div>
  );
}
