#pragma once
#include <string>
#include <memory>
#include <json/json.h>

/**
 * INTERVIEW DEFENSE NOTE:
 * This model follows the exact layout generated by drogon_ctl from our Postgres migration.
 * It provides strongly typed getters/setters for the 'users' table, avoiding manual SQL string parsing.
 */
namespace drogon_model
{
class Users
{
  public:
    struct Cols
    {
        static constexpr const char *_id = "id";
        static constexpr const char *_name = "name";
        static constexpr const char *_email = "email";
        static constexpr const char *_password_hash = "password_hash";
        static constexpr const char *_role = "role";
        static constexpr const char *_created_at = "created_at";
    };

    static const std::string primaryKeyName;
    static const bool hasPrimaryKey;
    static const std::string tableName;

    int getValueOfId() const { return id_; }
    void setId(int id) { id_ = id; }

    const std::string &getValueOfName() const { return name_; }
    void setName(const std::string &name) { name_ = name; }

    const std::string &getValueOfEmail() const { return email_; }
    void setEmail(const std::string &email) { email_ = email; }

    const std::string &getValueOfPasswordHash() const { return passwordHash_; }
    void setPasswordHash(const std::string &hash) { passwordHash_ = hash; }

    const std::string &getValueOfRole() const { return role_; }
    void setRole(const std::string &role) { role_ = role; }

  private:
    int id_{0};
    std::string name_;
    std::string email_;
    std::string passwordHash_;
    std::string role_;
};
} // namespace drogon_model
